# NLP Basics Notebook

The problems in Part One are taken from a previous quiz.  Write the value of each expression in the space provided. A helpful reminder.  When applied to strings, '<' checks alphabetical order.  So

```
>>> 'a' < 'b'
True
>>> 'b' < 'a'
False
>>> 'a' < 'a'
False
```

When applied to strings '+' does concatenation:

```
>>> 'a' + 'x'
'ax'
```


## Part One

In [1]:
letters = 'abcdefghijklmnopqrstuvwxyz'
vowels = 'aeiou'
word = 'facetious'
X = [l for l in letters if l not in vowels]
Y = [x for x in letters if x > 'd' and x < 'j']
W = [x for x in letters if x < 'd' or x > 'j']
Z = [x > 'd' and x < 'j' for x in letters]
R = [x for x in word if x in vowels]
letter_classes = {'vowels': vowels, 'consonants': X}

In [3]:
print(X)

['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z']


In [4]:
print(Y)

['e', 'f', 'g', 'h', 'i']


In [5]:
print(W)

['a', 'b', 'c', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [6]:
print(Z)

[False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]


In [7]:
print(R)

['a', 'e', 'i', 'o', 'u']


In [8]:
print(letter_classes)

{'consonants': ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'], 'vowels': 'aeiou'}


In [9]:
p1 = ['b' + x for x in vowels]
print p1

['ba', 'be', 'bi', 'bo', 'bu']


In [13]:
print Y[0]

e


In [15]:
print X[0:2]

['b', 'c']


In [23]:
p4 = [l for l in letters if l > 'f' and l < 'j']
print p4[0] + p4[1] + p4[2]

ghi


In [24]:
print Z[0:3]

[False, False, False]


In [26]:
p7 = [Y[0], Y[-1]]
print p7

['e', 'i']


In [29]:
p8 = [Y[1] == Y[2]]
print p8

[False]


In [30]:
p9 = [x < 'f' for x in vowels]
print p9

[True, True, False, False, False]


In [35]:
p10 = [l for l in letters if l == 'e']
print p10[0]

e


In [37]:
p11 = letter_classes['consonants'][-2]
print p11

y


###### Preliminaries

Write out `X`.  Remember `X` was created by a list comprehension, so it must be a list.

['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z']

Write out `Y`.  Remember `Y` filters the elements of `letters` with the condition `x > 'd' and x < 'j'`.

['e', 'f', 'g', 'h', 'i']

Write out `W`, also a filter.

['a', 'b', 'c', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

Write out `Z`. Remember the expression to the left of `for` in the list comprehension is what is evaluated once for each element of `letters`, with the results collected in the list `Z`.  So `Z` will be a list of things of the same type as `x > 'd' and x < 'j'`.

[False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

Write out `R`. Remember `R` filters the elements of `word` with the condition `x in vowels`.

['a', 'e', 'i', 'o', 'u']

Write out `letter_classes`.  Remember `letter_classes` is a dictionary.  Use curly braces.  Separate the keys from the values with `:`.

{'consonants': ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'], 'vowels': 'aeiou'}

1) What is the value of the following Python expression?

```
['b' + x for x in vowels]
```

 ['ba', 'be', 'bi', 'bo', 'bu']

2) What is the value of the following Python expression?

```
Y[0]
```

 e

3) What is the value of the following Python expression? (List splice must be a sublist of `X`)

```
X[0:2]
```

 ['b', 'c']

4) Write a Python expression which operates on `letters` and returns the following value

```
'ghi'
```

p4 = [l for l in letters if l > 'f' and l < 'j']
print p4[0] + p4[1] + p4[2]

5) Write a Python expression which operates on `letters` and returns the following  value.

```
['g','h','i']
```

 p4 = [l for l in letters if l > 'f' and l < 'j']
 print p4

6) What is the value of the following Python expression?

```
Z[0:3]
```

 [False, False, False]

7) Write a Python expression which operates on `Y` and returns the following value:

```
['e','i']
```

p7 = [Y[0], Y[-1]]
print p7

8) Write a line of code which operates on `Y` and returns `False`.

p8 = [Y[1] == Y[2]]
print p8

9) Write a line of code which returns the following value when applied to `vowels`:

```
[True, True, False, False, False]
```

p9 = [x < 'f' for x in vowels]
print p9

10) Write a line of code which operates on `letter_classes` and returns the following value.

```
'e'
```

p10 = [l for l in letters if l == 'e']
print p10[0]

11) Write a line of code which operates on `letter_classes` and returns the following value.

```
'y'
```

p11 = letter_classes['consonants'][-2]
print p11

12) What is the value of the following expression?

```
R[-1]
```

In [10]:
print R[-1]

u


##       Part Two

Write functions that behave according to the descriptions given.

1) Write a function that takes two numbers as arguments and multiplies them together and adds 1 to the result.  Call your function `product_successor`.  Then:

```
>>> product_successor(3,2)
7
>>> product_successor(5,9)
46
```

In [40]:
def product_successor(a, b):
    result = (a*b) + 1
    return result
print product_successor(3,2)
print product_successor(5,9)

7
46


2) Write a function that returns a list of the vowels from any string passed in.  You should use the list `vowels` from Part One as part of your answer.

```
>>> extract_vowels('hoover')
['o','o','e']
```

In [52]:
def extract_vowels(str):
    extractedVowels = [x for x in str if x in letter_classes['vowels']]
    return extractedVowels
print extract_vowels('hoover')

['o', 'o', 'e']


## Part 3

Reminders: `range(n)` returns a list of the integers from 0 up to but not including `n`.

```
>>> range(10)
[0,1,2,3,4,5,6,7,8,9]
```

`'str0'.join(str_seq)`  returns a string gotten by joining together the elements of `str_seq` with `str0`. It is the opposite of `split`.  It is an error if the elements of `str_seq` are not all strings:

```
>>> ''.join(['a','b','c'])
'abc'
>>> 'x'.join(['a','b','c'])
'axbxc'
>>> 'x'.join([1,2,3])
TypeError      
...
TypeError: sequence item 0: expected string, int found
>>> 'i'.join(['m','ss','ss','pp',''])
'mississippi'
>>> 'i'.join(['m','ss','ss','pp'])
'mississipp'
```




In [54]:
letters = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 
           'h', 'i', 'j', 'k', 'l', 'm', 'n', 
           'o', 'p', 'q', 'r', 's', 't', 'u', 
           'v', 'w', 'x', 'y', 'z')
vowels = 'aeiou'
digits = range(4)
word_list = ['acre','loft', 'soap', 'pleat']
weird_list = [word_list[x][x] for x in digits]
word3 = ''.join([x[1] for x in word_list])
word4 = 'i'.join(['m','ss','ss','pp',''])
char_list = [x for x in word4 if x in vowels]
word1 = 'rambunctious'
word2 = 'mellifluous'
WW = word1 + word2
Z = [x for x in WW if x in 'lmn']
favorite_words = {'Noam Chomsky': word2, 'Leonard Bloomfield': word1, 'John Rupert Firth': word3}

In [89]:
print weird_list

['a', 'o', 'a', 'a']


Write out `word3` below.

In [55]:
print word3

cool


Write out `word4` below.

In [56]:
print word4

mississippi


Write out `digits` below.

In [57]:
print digits

[0, 1, 2, 3]


Write out `weird_list` below.

In [58]:
print weird_list

['a', 'o', 'a', 'a']


Write out `char_list` below.

In [59]:
print char_list

['i', 'i', 'i', 'i']


Write out `Z` below.

In [61]:
print Z

['m', 'n', 'm', 'l', 'l', 'l']


Write an expression which operates on `favorite_word` and returns:

```
'cool'
```

In [63]:
print favorite_words['John Rupert Firth']

cool


Write an expression which operates on `favorite_word` and returns:

```
'bun'
```

Hint: Use a splice.  Remember that `favorite_word` is a dictionary. Values are retrieved from a dictionary by keys, and therefore it makes no sense to use numerical indices (or splices) directly on a dictionary.  But you might be able to use a splice on something inside the dictionary.

In [64]:
print favorite_words['Leonard Bloomfield'][3:6]

bun


Write an expression which retrieves

```
['a','b','c','x','y''z']
```

from `letters`.  Hint: use a list comprehension with a condition.

In [65]:
endTriples = [x for x in letters if x < 'd' or x > 'w']
print endTriples

['a', 'b', 'c', 'x', 'y', 'z']


## Part 4

In [67]:
employees = ['happy', 'sleepy', 'dopey', 'bashful', 'grumpy', 'doc', 'sneezy']
employeeEmail = {'happy': ['sleepy','dopey'], 'dopey':['dopey'],'doc': employees,
                 'sleepy': ['bashful','doc', 'happy'],'grumpy':[],
                 'bashful': ['dopey']}
secret_word = 'utilitarian'
flip = {'0':'1', '1':'0'}
bit_string = '001110'
flipped = [flip[x] for x in bit_string]

Write out the values of the following expressions, noting errors where appropriate.  Pay attention to your types (use delimiters like `{`, `[`, and `(` appropriately).

```
employees[2:5]
    ['dopey', 'bashful', 'grumpy']

employeeEmail['happy'][1][-1]
    y

employeeEmail[1][1][-1]
    KeyError: 1

employeeEmail['happy']['sleepy'][-1]
    TypeError: list indices must be integers, not str

secret_word[-5:]
    arian

[x < 'j' for x in secret_word]
    [False, False, True, False, True, False, True, False, True, True, False]

flipped
    ['1', '1', '0', '0', '0', '1']
```

Write a function which takes two numbers `m` and `n` and returns the result of adding `m` and `n` together and multiplying the result by 3.

In [72]:
def combo_triple(m, n):
    result = (m + n)*3
    return result

print combo_triple(2, 6)

24


Part 5

In [73]:
import numpy as np
x = np.array([5,13,23,47,9])
y = np.ones((5,))
z = np.ones((5,2))

For each of the following expressions, write down what is returned.

In [74]:
x * 2

array([10, 26, 46, 94, 18])

In [75]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [76]:
x + y

array([  6.,  14.,  24.,  48.,  10.])

In [77]:
z

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [78]:
x + z

ValueError: operands could not be broadcast together with shapes (5,) (5,2) 

Explain why you get the result that you get for `x + z`. (Answer: `x` and `z` have incompatible shapes.
`x` is a `1D` array with shape `(5,)`, and `z` is a 2D array with shape `(5,2)`.

In [79]:
z.shape

(5, 2)

Note the following:

In [80]:
x < 20

array([ True,  True, False, False,  True], dtype=bool)

The result above is called a **Boolean array** because it only contains instances of the
type `bool` (`True` and `False`). Such Boolean arrays can be used to index arrays (basically
if they are of the same length).  Using a Boolean array this way is called using a **Boolean mask**.

Using a Boolean mask, write an expression that returns an array containing the members of `x` that
are less than `20`.

In [81]:
x[x<20]

array([ 5, 13,  9])

In [82]:
two_d_array = np.array([[1,2],[2,1],[5,5],[9,4]])

Write an expression that returns the second row of `two_d_array`.

In [83]:
two_d_array[1,]

array([2, 1])

Write an expression that returns `two_d_array` omitting the first row.

In [84]:
two_d_array[1:,]

array([[2, 1],
       [5, 5],
       [9, 4]])

Write an expression that returns the following subarray of `two_d_array`.

```
array([[2, 1],
       [5, 5]])
```

In [88]:
two_d_array[1:3:1, 0:2:1]

array([[2, 1],
       [5, 5]])